## Refer to Using dbt with Dagster, part one for info about this file:
## https://docs.dagster.io/integrations/dbt/using-dbt-with-dagster/part-one

name: "project"
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  +start: Jan 1 2000
  default:
    +materialized: table

seeds:
  default:
    +enabled: true
    +schema: bronze
    orders:
      id: int
      product_id: int
      quantity: int
      created_date: varchar(10)
    products:
      id: int
      name: varchar(32)
      category: varchar(32)
      price: float