services:

  postgres:
    image: postgres:15
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  sqlpad:
    image: sqlpad/sqlpad:5
    hostname: 'sqlpad'
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      - postgres        

  dbt:
    build:
      context: .
      dockerfile: ./dbt/Dockerfile
    volumes:
      - ./dbt:/app
    env_file: .env
    depends_on:
      - postgres  
    ports:
      - "8001:8001"

volumes:
  postgres_data: